name: build

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v25

    - name: mkosi
      run: |
        nix develop -c mkosi -C ./initrd build
        nix develop -c mkosi build
